version: '3.5'

services:

  postgres_db:
    image: postgres
    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=school
      - POSTGRES_DB=school

    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump

    ports:
      - "5432:5432"

    networks:
      - docker-practice-net


  redis:
    image: "redis:alpine"

    ports:
      - "6379:6379"

    networks:
      - docker-practice-net


  spring_app:

    build:
      context: ./images/app
      dockerfile: Dockerfile

    ports:
      - "8888:8888"

    network_mode: "host"

    depends_on:
      - postgres_db
      - redis


networks:
  docker-practice-net:
    name: docker-practice-net
