FROM openjdk:11-jre-slim
COPY /docker-practice-java-0.0.1-SNAPSHOT.jar /opt/docker-practice-java-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/opt/docker-practice-java-0.0.1-SNAPSHOT.jar"]
